# Generated by Django 4.1.7 on 2023-04-02 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='شماره مبایل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالیت')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True, verbose_name='شماره')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان تولید')),
                ('days_charge', models.IntegerField(default=0, verbose_name='روز های شارژ شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شماره سریال',
                'verbose_name_plural': 'شماره سریال ها',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=600, verbose_name='کد')),
                ('expiry', models.BooleanField(default=False, verbose_name='انقضا')),
                ('activation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فعال سازی')),
                ('serial_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='account.serialnumber', verbose_name='شماره سریال')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کد تایید ها',
            },
        ),
    ]
