# Generated by Django 4.1.7 on 2023-04-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opt',
            name='full_name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
