# Generated by Django 4.1.7 on 2023-04-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_opt_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opt',
            name='full_name',
        ),
    ]
