# Generated by Django 4.1.7 on 2023-04-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_opt_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره'),
        ),
    ]
