# Generated by Django 4.1.7 on 2023-04-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_serialnumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
