# Generated by Django 4.1.7 on 2023-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_confirmationcode_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
